### ISSUE TITLE
Failed to activate the closed package

### ISSUE THREAD

**Issue by crosset** [Raynes/closed#4]
[Enter steps to reproduce below:]

1. Install the package
2. Use keybinding ctrl-command-p to open a file

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [closed](https://github.com/Raynes/closed) package, v0.3.6

### Stack Trace

Failed to activate the closed package

```
At Cannot read property 'append' of undefined

TypeError: Cannot read property 'append' of undefined
  at ClosedView.module.exports.ClosedView.initialize (/Users/rosset/.atom/packages/closed/lib/closed-view.coffee:44:23)
  at ClosedView.View (/Users/rosset/.atom/packages/closed/node_modules/space-pen/lib/space-pen.js:178:25)
  at ClosedView.SelectListView (/Users/rosset/.atom/packages/closed/node_modules/atom-space-pen-views/lib/select-list-view.coffee:9:3)
  at new ClosedView (/Users/rosset/.atom/packages/closed/lib/closed-view.coffee:10:3)
  at Object.module.exports.activate (/Users/rosset/.atom/packages/closed/lib/closed.coffee:7:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  3x -7:46.4.0 tree-view:toggle-focus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:38.1.0 pane:split-right (atom-pane.pane.active)
  2x -7:35.7.0 pane:split-left (atom-pane.pane.active)
  3x -7:15.8.0 core:close (atom-pane.pane.active)
  3x -7:03.3.0 tree-view:toggle (atom-pane.pane.active)
     -6:40.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:15.6.0 closed:Open File (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -5:02.5.0 application:new-file (div.settings-view.pane-item)
  5x -5:00.5.0 closed:Open File (atom-text-editor.editor.is-focused)
  5x -3:27.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:37 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -0:00.6.0 closed:Open File (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
closed, v0.3.6
emacs, v0.8.1
language-cython, v0.3.0
minimap, v4.9.4
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by Raynes** [comment]
Thanks for reporting!
